In [4]:
## para guardar
#   tf.train.Saver
#guarda las variables

import tensorflow as tf

save_file = 'C:\\Users\\jrgomez\\Documents\\Udacity Nanodegree\\deep-neural-networks\\model.ckpt'

weights   =   tf.Variable(tf.truncated_normal([2,3]))
bias  =   tf.Variable(tf.truncated_normal([3]))

saver   =   tf.train.Saver()

with tf.Session() as sess:
    
    sess.run(tf.global_variables_initializer())
    
    print('weights:')
    print(sess.run(weights))
    print('Bias')
    print(sess.run(bias))
    
    #save the model
    saver.save(sess, save_file)

weights:
[[-0.16968805  1.34754038 -1.40657413]
 [-0.87387323  0.41866732  0.10778923]]
Bias
[ 0.10220123 -0.7111364  -0.48477641]


### Loading

In [5]:

#remove previous weights and bias
tf.reset_default_graph()

weights   =   tf.Variable(tf.truncated_normal([2,3]))
bias   =   tf.Variable(tf.truncated_normal([3]))


saver   =   tf.train.Saver()

with tf.Session() as sess:
    #carga
    saver.restore(sess, save_file)
    
    #muestra los valores
    print('Weight:')
    print(sess.run(weights))
    print('Bias:')
    print(sess.run(bias))

INFO:tensorflow:Restoring parameters from C:\Users\jrgomez\Documents\Udacity Nanodegree\deep-neural-networks\model.ckpt
Weight:
[[-0.44470525  0.28271329 -0.76841176]
 [-0.86061001 -1.45000815 -1.12529707]]
Bias:
[-0.21545587 -0.39586413  0.06289285]


### Save a Trained Model